name: Build and Deploy to S3

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to deploy"
                required: true
                default: "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.branch || 'main' }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4 # docs https://pnpm.io/continuous-integration#github-actions
              with:
                  version: 10

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build the app
              run: pnpm run build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-4

            - name: Sync S3 bucket
              run: |
                  aws s3 sync dist/ s3://stopwatch --delete

            - name: Invalidate CloudFront
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
